#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: Build_x86_64

on: 
  release:
    types: [published]

  push:
   branches: 
     - master

  #schedule:
  #  - cron: 0 8 * * 5
  
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install git
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
        
    # - name: Update & Install feeds
    #   working-directory: ./openwrt
    #   run: |
    #     ./scripts/feeds update -a
    #     ./scripts/feeds install -a
    #     ./scripts/feeds install -a

    #- name: Import external feeds
    #  working-directory: ./openwrt
    #  run: |
    #    git clone https://github.com/xiaorouji/openwrt-passwall.git package/lienol
    #    git clone "your_github_link" package/"your_folder_name"      

    # - name: Configuration Customization - Build_x86_64
    #   env:
    #     CONFIG_FILE: 'x86_64.config'
    #   run: |
    #     [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
    #     chmod +x ./customize.sh && ./customize.sh
    #     cd openwrt && make defconfig
        
    # - name: Download package
    #   working-directory: ./openwrt
    #   run: |
    #     make download -j$(nproc)
    #     find dl -size -1024c -exec ls -l {} \;
    #     find dl -size -1024c -exec rm -f {} \;

    # - name: Build firmware
    #   working-directory: ./openwrt
    #   run: |
    #     echo -e "$(nproc) thread build."
    #     make -j$(nproc) V=s

    # - name : Upload artifact
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: OpenWrt
    #     path: openwrt/bin

    - name: compress
      id: compress
      run: |
        tar -czvf openwrt.tar.gz ./openwrt

    - name: Upload firmware to cowtransfer
      id: cowtransfer
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress openwrt.tar.gz 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"

    - name: Upload firmware to WeTransfer
      id: wetransfer
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress openwrt.tar.gz 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"
